version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python bot/main.py
    volumes:
      - .:/app
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
